@startuml

state EtatVoyage {

[*] --> Publie : Création par Conducteur

state Publie {
  state "Disponible" as Dispo
  state "Complet" as Full

  [*] --> Dispo

  Dispo --> Full : Nouvelle Réservation\n[Total places réservées == Places Max]
  Full --> Dispo : Annulation Réservation\n[Total places réservées < Places Max]
}

Publie --> Termine : Heure Départ passée
Termine --> [*]

note right of Full : État calculé via requête SQL\nsur table Réservation\n
}
@enduml