@startuml

scale 1.3
state EtatVoyage {

[*] --> Publie : Création par Conducteur
state Publie {
  state "Disponible" as Dispo
  state "Complet" as Full

  [*] --> Dispo

  Dispo --> Full : Nouvelle Réservation\n[Total places réservées == Places Max]

}

Publie --> Termine : Heure Départ passée
Termine --> [*]

}
@enduml